INSERT INTO TBL_MUSIC (TITLE, SINGER, ALBUM, DATE, DURATION) VALUES ('Thunderstruck', 'AC/DC', 'Tha Razors Edge', 1990, 292);
INSERT INTO TBL_MUSIC (TITLE, SINGER, ALBUM, DATE, DURATION) VALUES ('Everlong', 'Foo Fighters', 'The Colour And The Shape', 1997, 250);
INSERT INTO TBL_MUSIC (TITLE, SINGER, ALBUM, DATE, DURATION) VALUES ('Africa', 'TOTO', 'Toto IV', 1982, 290);
